{"name": "test_db_after_submit", "status": "broken", "statusDetails": {"message": "TypeError: __init__() got an unexpected keyword argument 'username'", "trace": "def test_db_after_submit():\n        # 先上报数据\n        client = HttpClient()\n        client.post(\"/api/bloodpressure\", {\"systolic\": 180, \"diastolic\": 110})\n    \n        # 检查数据库\n>       db = DBHandler()\n\ntest_cases\\test_bloodpressure.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utils.db_handler.DBHandler object at 0x00000178A9442B20>\n\n    def __init__(self):\n>       self.conn = pymysql.connect(**DB_CONFIG)\nE       TypeError: __init__() got an unexpected keyword argument 'username'\n\nutils\\db_handler.py:6: TypeError"}, "start": 1744274618770, "stop": 1744274618829, "uuid": "b1f6ab8d-c719-4264-8145-d68ca3f9bc86", "historyId": "492203d9878f6627557ab1f43dd7b343", "testCaseId": "492203d9878f6627557ab1f43dd7b343", "fullName": "test_cases.test_bloodpressure#test_db_after_submit", "labels": [{"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_bloodpressure"}, {"name": "host", "value": "PC-20220908HPOQ"}, {"name": "thread", "value": "14728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_bloodpressure"}]}